### ISSUE TITLE
why can't I lock the windows use keyboard lib?

### ISSUE THREAD

**Issue by drawwon** [boppreh/keyboard#102]
I wrote this program below, but when I run this script, it did nothing and return nothing. `keyboard.press_and_release('win+l')`
but when i run win+e, it run perfect.
so how could I fix this problem?

In the meanwhile, I can't input anything when I lock the screen, how can I input the password of my computer and 'enter' to get into windows?
```
dll = ctypes.WinDLL('user32.dll')
dll.LockWorkStation()
time.sleep(1)


keyboard.send('enter')
keyboard.send('1,2,3')
keyboard.send('enter')
```

**Comment by boppreh** [comment]
These are security features from Windows. You also can't block ctrl+alt+del, for example. As far as I know there are no workarounds either, by design.

I'm not sure what kind of threats Windows is preventing with this, but I think you will have better chances trying to disable these features than trying to override them in your code.

Sorry.

**Comment by boppreh** [comment]
It's hard to make and keep an exhaustive list, but I'll try to add something about these limitations in the Readme.
