### ISSUE TITLE
asynchronous event

### ISSUE THREAD

**Issue by akayunov** [boppreh/keyboard#121]
Hi, in documentation you say what "Note: the callback is executed in a separate thread, asynchronously." Does it means what I can handle some key press event in one time?
I try to run next code(see attach
[test.txt](https://github.com/boppreh/keyboard/files/1681528/test.txt)
) and I see that all event handled one by one, but I try to influence one event to another:

Output is:
start1
start4
('start:', 0)
`('start:', 1)
('start:', 2)
('start:', 3)
('start:', 4)
('up', '`', 41, 1517398717.536053)
start7
('GLOBAL_WHILE_FLAG', False)

but i suspect to see:
start1
start4
('start:', 0)

**Comment by boppreh** [comment]
They are executed asynchronously with respect to the thread that called 'add_hotkey' (i.e. it doesn't block), but all callbacks are processed by the same thread. I had to add this line because some beginners were getting confused. 

I'm afraid you'll have to spawn a new thread on each callback if you want them to influence each other. There's a helper function, "call_later", that can be called with a parameter of zero delay to help this.

**Comment by akayunov** [comment]
Thx, got it.
