### ISSUE TITLE
Question: what's the correct usage of 'get_typed_strings'?

### ISSUE THREAD

**Issue by pjmtavares** [boppreh/keyboard#128]
Hi boppreh, everyone... Congratulation on 'keyboard', excellent work!

I'm trying to save all the words I type at my computer to a file, in an endless loop, for personal time tracking. I managed to do this with 'pyHook', at first, but had to patch my copy to avoid breaking dead keys, rebuild it, and write quite some code to deduce which strings I typed in spite of edits. Then I discovered 'keyboard', which I found quite good, and started migrating my code to it. I thought  'get_typed_strings' might also already do a good part of what I was implementing, so I tried using it. 

I'm not experienced in generators, but after reading I couple of introductions, I wrote the following example code:
```
import keyboard

record = keyboard.start_recording()
words = keyboard.get_typed_strings(record)

while True:
    word = next(words)
    print(word)
```
However, I get an error: `AttributeError: 'Queue' object has no attribute 'name'`

If 'get_typed_strings' can be used in the way I intend, can someone please tell me what I'm doing wrong? Thank you for your time!

**Comment by boppreh** [comment]
Hi @pjmtavares 

Thank you for the kind words.

In this specific case, the problem is that `start_recording` returns a tuple `(queue, hook)`, so `get_typed_strings` tries to read the first element thinking it's an event, but fails. But even if you took only the queue then it still wouldn't work because queues are not iterable. This is a good point, these interfaces should play better with each other.

It's not as elegant, but creating your own event generator should be easy enough:

```
import keyboard

def generate_events():
    while True:
        yield keyboard.read_event()

strings = keyboard.get_typed_strings(generate_events())
while True:
    print(next(strings))
```

Also note that `get_typed_strings` groups together any sequence of single-character events, including spaces, so the result is not just words but entire lines.

The `get_typed_strings` function was created because a single user requested it a while ago, and I feel like it hasn't been used much. Any feedback on it is appreciated.

**Comment by pjmtavares** [comment]
Thanks for the prompt answer and detailed explanation! I tried your sample code and it worked as it should (I just had to replace `read_event` with `read_key`).
