### ISSUE TITLE
Media keys on Windows

### ISSUE THREAD

**Issue by jbardnz** [boppreh/keyboard#134]
Not sure if I am doing something wrong, I am trying to test media keys on Windows 10.

I have a super simple script just containing:

`keyboard.press_and_release('play/pause media')`

Then I play audio using VLC player, when I run my script I expect VLC to pause but nothing happens (no errors either).

Any ideas?

**Comment by boppreh** [comment]
If you have a corresponding media key on your keyboard, try running 'hook(print)' or 'python -m keyboard' to see what the actual name of the key is.

I'll still take a look. These complex keys should be constants to avoid typos too.

**Comment by jbardnz** [comment]
I don't have media keys on my keyboard, going to borrow an external one tomorrow so I can test with that.

**Comment by boppreh** [comment]
If the script is not throwing any errors then it found the key, so it's not just a typo. Could also be VLCs fault, I had it misinterpreting Bluetooth media keys before.

**Comment by boppreh** [comment]
Notes: 'play/pause media' has no scan code and VK 179. However, this doesn't work:

```
import ctypes
user32 = ctypes.WinDLL('user32', use_last_error = True)
user32.keybd_event(179, 0, 0, 0); user32.keybd_event(179, 0, 2, 0)
```

Pressing the key on my keyboard also reports a "G" keypress, and I'm not sure why.

**Comment by jbardnz** [comment]
Apologies for the slow reply, just managed to get a keyboard with media keys for testing.

First thing, when running `python -m keyboard` I get this:

`{"event_type": "up", "name": "play/pause media", "scan_code": -179, "time": 1521095731.5274982}`

This still does nothing:
`keyboard.press_and_release('play/pause media')`

But this works (note -179 not 179):
`keyboard.press_and_release(-179)`

**Comment by iliazeus** [comment]
Here's a snippet of `from_name` from my Windows machine (from running `python -m keyboard._winkeyboard`):

```
 'play/pause media': [(1, (34, 179, 0, ())),
                      (1, (34, 179, 1, ())),
                      (3, (34, 179, 0, ())),
                      (3, (34, 179, 1, ())),
```

In this table, `play/pause media` has a scan code of the G key (34).

It is set that way, because `user32.MapVirtualKeyExW(179, MAPVK_VK_TO_VSC_EX, 0)` returns `57378` (179 is a vk code for play/pause). Then it is trimmed to 1 byte in here:
https://github.com/boppreh/keyboard/blob/6f9961f2589cf37749239acf938a7e40ae9e9a21/keyboard/_winkeyboard.py#L389

But `57378 & 0xFF` is `34` (scan code for G).

**Comment by iliazeus** [comment]
@boppreh Why are scan codes and vk codes trimmed to 1 byte anyway? According to this:
https://msdn.microsoft.com/ru-ru/library/windows/desktop/ms646307(v=vs.85).aspx
they are UINT values, so they should be 4 bytes wide:
https://msdn.microsoft.com/en-us/library/windows/desktop/aa383751(v=vs.85).aspx#UINT

**Comment by boppreh** [comment]
@jbardnz This still doesn't work for me:

    keyboard.press_and_release('play/pause media')

Maybe it's a problem on my machine.

@iliazeus You are right, and I don't remember why that mask was there in the first place. Maybe a copy-paste error from `GetKeyNameText`. I'm removing the mask completely for the moment, since all values come from Windows itself. It's still weird that pressing `play/pause` also reports a press of a key with scan code 34 ("G").

**Comment by boppreh** [comment]
I made some changes to the Windows backend and now

```python
keyboard.press_and_release('play/pause media')
```

is working again for me. Can you check if fixes your problem?

**Comment by jbardnz** [comment]
Yes that is working great for me on Windows now :)

**Comment by boppreh** [comment]
Great, thank you for the report and testing!

**Comment by boppreh** [comment]
@iliazeus 

I made commit 14cd6f5 removing the masks and forgot to link here. That fixed this specific issue, but made `keyboard.send('windows')` break (#147). I'm investigating now.

Note that functions like [MapVirtualKeyEx](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646307(v=vs.85).aspx) use the high-order byte of the returned scan code (which is apparently 0xe000 and not 0xe0000000 as expected from an UINT) to signify extended key ranges, which is now causing trouble when trying to simulate key presses of the windows key.
