### ISSUE TITLE
Linux win key causes keyboard module throw an exception.

### ISSUE THREAD

**Issue by mibli** [boppreh/keyboard#15]
Example program
```python
import keyboard
import time
import logging
BINDS = []
BINDS.append(keyboard.add_hotkey("win", lambda: logging.error("pressed")))
while True:
    time.sleep(1)
```

Result when pressing win key
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/mblizniak/repos/i3-pyswitch/3rd-party/kb/_nixkeyboard.py", line 94, in listen
    name = to_name[(scan_code, tuple(sorted(pressed_modifiers)))]
KeyError: (125, ())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mblizniak/repos/i3-pyswitch/3rd-party/kb/__init__.py", line 79, in listen
    _os_keyboard.listen(self.queue)
  File "/home/mblizniak/repos/i3-pyswitch/3rd-party/kb/_nixkeyboard.py", line 96, in listen
    name = to_name[(scan_code, ())]
KeyError: (125, ())
```

[dumpkeys--keys-only.txt](https://github.com/boppreh/keyboard/files/587344/dumpkeys--keys-only.txt)

**Comment by boppreh** [comment]
Thanks for the detailed report. Apparently dumpkeys is not reporting the Windows and app key. Checking an alternative.

**Comment by boppreh** [comment]
As far as I can see this is a problem with `dumpkeys` reporting the Windows key as `alt`. It also doesn't report `menu`, and prefers to name `home` as `find`. Though in its defense it does report the `home -> find` synonym at the end of the long-form report.

Which means I know of no clean way of supporting `windows` and `menu` key on Linux. Since these are fairly important, I've pushed some code that manually adds them in case they are missing. Please check if it's working for you.

I also fixed two other bugs found during this fix. One was that unknown keys should not raise exceptions like this, and the other was that `matches` wasn't falling back to scan codes correctly.

**Comment by mibli** [comment]
It seems to work well now as far as I can see. Thanks :beer:

**Comment by boppreh** [comment]
Great to hear. Thank you for the bug report.
