### ISSUE TITLE
End, Home etc keys sharing the same scan_code with number on numpad

### ISSUE THREAD

**Issue by pshe94** [boppreh/keyboard#154]
Hi, if I use `on_press_key` with, for example, an `end` key as a first argument, then run the program and press `1` on numpad, `on_press_key` is being called (even if I'm not pressing shift key with it. And yes, Num Lock is turned on). 
After further inspection it looks like `end` key and `1` on numpad share the same `scan_code`, but different `name`. The same thing happens with `home` and 7, `page down` and 3, `page up` and 9, and probably other ones too. 
Is that expected behavior?

**Comment by boppreh** [comment]
Hi

Yes, this is expected behavior. `on_press_key` (and similar `_key` functions) looks for key labels regardless of modifiers. I understand this can be confusing, but it's the logical conclusion I had to take.

There are several types of keys that share names, or that have their names modified:

- Letters become uppercase when shift is pressed, or caps lock is on. `on_press_key('A')` should match even an unshifted `a`, and `on_press_key('a')` should not stop working when shift is held or caps lock is on.
- Therefore, `on_press_key('1')` should also be equivalent to `on_press_key('!`)` (modulo keyboard layout).
- Num lock is a modifier, so pressing `num 1` should trigger a hook for `end` (but not vice-versa!).

I don't know of any other way to make this less confusing without breaking consistency.

**Comment by pshe94** [comment]
OK, I understand now. Thank you
