### ISSUE TITLE
Key Seprate 

### ISSUE THREAD

**Issue by GreenRanger2478** [boppreh/keyboard#159]
Hello!
 i am trying to use the keyboard module to just assign NumberPad 0 to execute a function. this does work, however if i press the 0 key it also executes the function. I have also noticed that the HOME key on the number pad and the section above the arrows are linked as well. Setting a hotkey for home will be executed form both keys as well.
Is their any way to separate this? where the number pad keys are separated.

thanks

**Comment by boppreh** [comment]
Hi @GreenRanger2478 

Hotkeys work more or less by the label on the key. If you register a hotkey for "home", it'll trigger whenever a key labeled "home" is pressed, and this includes numpad 7 (even though you don't have numlock!).

I understand this is confusing, but it would be even more confusing if a hotkey for "shift+5" failed because key "5" actually becomes "%" when shift is pressed. Suggestions welcome.

There are plans to allow users to specify "numpad 5" as a key name for example, but this is not implemented yet.

A workaround if you want to trigger on a specific key is to use the raw scan code. You can get this scan code by printing an event, or running `python -m keyboard` and looking at the output when you press that key. Not ideal, but I hope it helps your case.

**Comment by GreenRanger2478** [comment]
Thanks for the quick replay and the explanation. However i was able to separate Numpad Keys by modifying this in your code in _canonical_names.py:
 `    'num 0': 'num 0',
    'num 1': 'num 1',
    'num 2': 'num 2',
    'num 3': 'num 3',
    'num 4': 'num 4',
    'num 5': 'num 5',
    'num 6': 'num 6',
    'num 7': 'num 7',
    'num 8': 'num 8',
    'num 9': 'num 9',`

This does the trick, however the other labels such as the HOME key remains the same.
