### ISSUE TITLE
Using multimedia keys (volume up/down)?

### ISSUE THREAD

**Issue by wiiittttt** [boppreh/keyboard#16]
Is it possible to simulate using these keys I don't have a multimedia keyboard actually attached? How would I go about finding the code to send? I currently am using an AutoHotKey script for it but would love to replace it with a python script instead.

EDIT: I'm on Windows.

**Comment by boppreh** [comment]
Neither Windows nor Linux report the media keys as actual keys, but as application messages instead. So unfortunately it's not supported at the moment.

**Comment by wiiittttt** [comment]
Ah, no problem. Thank you for the fast response!

**Comment by boppreh** [comment]
If you don't mind I'll leave the issue open to better track pending limitations.

Thank you for your report though. I fully expected at least Linux to report media keys correctly, but to my surprise they emit no keyboard event at all.

**Comment by boppreh** [comment]
Huh.

So, while debugging the keypad attribute I discovered that media keys *are* reported by Windows, but they always have scan code of 0, which my library was filtering out. Thankfully they still have a sane virtual key code.

It took some wiggling to add playback support because of the missing scan code, but I think it's working. Key presses should be reported as usual, and playback should also work. The patch is available as version 0.9.6.

Feel free to reopen the issue if you experience problems.

**Comment by wiiittttt** [comment]
Volume keys working perfectly. Thanks!

**Comment by boppreh** [comment]
Great to hear :)
