### ISSUE TITLE
Root required on Linux

### ISSUE THREAD

**Issue by brianbruggeman** [boppreh/keyboard#17]
The requirement of root access won't work for a large number of applications.

I didn't look through what made that a requirement, but it looks like `ensure_root` is littered all over the code base for a posix environment.

Somewhat related - I wasn't able to setup a virtualenv properly because of this requirement.

**Comment by boppreh** [comment]
The root requirement is to access the raw devices under `/dev/input/*` and similar. As far as I know there's no way around it.

But I'm actually glad. Being able to intercept all key strokes from all hardware seems like a huge privilege. Requiring root seems appropriate.

It might be possible to sidestep this rule if you use X, because there's no security in X, but that would put extra requirements. Currently the library works even in a GUI-less Raspberry Pi, and I would prefer not to sacrifice that.
