### ISSUE TITLE
ImportError: You must be root to use this library on linux.

### ISSUE THREAD

**Issue by Yolotroll101** [boppreh/keyboard#177]
I am using anaconda on chromebook to be able to use python3.6 on it. My issue is that I am trying to replicate something from the **curses** module. The thing I am trying to replicate is when I press a key, _any_ key, it reads it back to me immediately, like I press "e", it shows **e**. If I then press "o", it replaces the **e** with an **o**.

So this me just guessing to see if it works, but my code rn is:
```py
import keyboard

mans = False
while not mans:
    dwn = keyboard.KEY_DOWN
    dun = keyboard.on_press(dwn)
    print(dun)
```
and it returns as:
```
Traceback (most recent call last):
  File "keyboardtest.py", line 6, in <module>
    dun = keyboard.on_press(dwn)
  File "/usr/local/conda3/lib/python3.6/site-packages/keyboard/__init__.py", line 472, in on_press
    return hook(lambda e: e.event_type == KEY_UP or callback(e), suppress=suppress)
  File "/usr/local/conda3/lib/python3.6/site-packages/keyboard/__init__.py", line 459, in hook
    append(callback)
  File "/usr/local/conda3/lib/python3.6/site-packages/keyboard/_generic.py", line 67, in add_handler
    self.start_if_necessary()
  File "/usr/local/conda3/lib/python3.6/site-packages/keyboard/_generic.py", line 35, in start_if_necessary
    self.init()
  File "/usr/local/conda3/lib/python3.6/site-packages/keyboard/__init__.py", line 194, in init
    _os_keyboard.init()
  File "/usr/local/conda3/lib/python3.6/site-packages/keyboard/_nixkeyboard.py", line 113, in init
    build_device()
  File "/usr/local/conda3/lib/python3.6/site-packages/keyboard/_nixkeyboard.py", line 109, in build_device
    ensure_root()
  File "/usr/local/conda3/lib/python3.6/site-packages/keyboard/_nixcommon.py", line 174, in ensure_root
    raise ImportError('You must be root to use this library on linux.')
ImportError: You must be root to use this library on linux.
```
Note how it says "**ImportError: You must be root to use this library on linux.**"

Now, normally, using a `sudo` would fix it, but `python3` is not recognized as a command in sudo for me. When I try using the `python` command (without 3 for 3.6) it says that the `keyboard` module is non existent, even though it works for python3.6.

I will appreciate any help avaible!

**Comment by Yolotroll101** [comment]
ok, but when I tried using `pip install keyboard` (aka: install it for python 2, not 3) it says it's already installed

**Comment by Yolotroll101** [comment]
yea but my question is, why does it say I need to be root?

**Comment by Yolotroll101** [comment]
and I did try having it pass `print`, and it gave same error

**Comment by boppreh** [comment]
The library needs root because it operates the same way as a keylogger: intercepting every keystroke, system wide. On Linux, with tools used here (`/dev/input` files), the kernel restricts this operation only to scripts executed by the superuser. There's an alternative on the works, to use xlib, but it's not ready yet.

Therefore you must execute the script as superuser. How to do that depends on your system, and is not a question suitable for an issue on this library.

**Comment by Yolotroll101** [comment]
ok, so in your first reply, you mentioned how I could use `pip` (instead of `pip3`) to install it onto another version of python, but when I try this, it says the requirement is already satisfied. When I try doing `python keyboardtest.py`, it says `ImportError: No module named 'keyboard'`. (but it's a known module when I use `python3 keyboardtest.py`.)

**Comment by boppreh** [comment]
On my first reply I said to use `python2 -m pip`, which first fires up Python 2, then asks for the `pip` module. This guarantees the pip you are getting is the one associated with your python2 binary. Your `pip` binary is probably mapped to pip3. You can check that by doing `which pip`.

But you can get much better help by googling or going to stack overflow. I'm afraid this is not the right place.

**Comment by Yolotroll101** [comment]
ok, I'm just going to close this as I am realizing I have no hope of getting my answer here, but I do want to say, the command of python2 is unrecognized, so that won't work

**Comment by boppreh** [comment]
Hi @Yolotroll101 

I'm sorry for being so blunt. I support this library on my free time. Every minute spent helping people set up their environment (which is totally unrelated), is a minute that is not spent on improving the library, or helping people whose only hope of support is posting here.

You have a Python script, with dependencies, that you need to run as root. That's something you can get help for in a lot of different places.

To avoid leaving this on a sour note, a few more workarounds that may work for you:

- download the library as a zip file and import it as a local script, instead of installing.
- write a shell script to invoke the Python interpreter over your script, using only absolute paths, and run *that* with sudo.
- spend some time doing `which python`, `which python3`, `sudo which pip3`, etc, to get a feel for where things are for your user and the superuser.
