### ISSUE TITLE
Reading multiple key presses when key is being pressed once

### ISSUE THREAD

**Issue by JorgeG30** [boppreh/keyboard#180]
Hello, as the title states I am reading more than one key press even though I am only pressing the key once. Is this due to the sensitivity of the keyboard or something else. Here is the code I am currently testing

`while True:
     if keyboard.is_pressed('d')
     dC = dC + 1

     if keyboard.is_pressed('enter')
     break`

The counter is initialized before the loop begins and I have the press of the enter key as a break condition. After the loop I print out the counter and I get something like 62 or 47 even if I hit the key only once. Any idea why this might be happening.

**Comment by boppreh** [comment]
Hi Jorge

Sorry for not answering, I had to take some time away.

The problem stems from using "while True". Your program is checking if the key is being held down, and doing as many checks per second as the CPU can handle. When you eventually press the key, even if you release it quickly, the CPU managed to check the key 47~62 times.

Depending on what you want to achieve I suggest using `add_hotkey` (fires only once after a key combo is pressed) or `read_event`/`read_key` so that event are not double-counted.
