### ISSUE TITLE
nothing happens

### ISSUE THREAD

**Issue by el3ctron** [boppreh/keyboard#19]
hi, i am python newbie, and **is very dificult to me understand how to run this program**, so, i create a executable file on linux called k3y like this

```
#!/usr/bin/python
# coding: latin-1

import keyboard

# Press PAGE UP then PAGE DOWN to type "foobar".
keyboard.add_hotkey('page up, page down', lambda: keyboard.write('foobar'))

keyboard.add_hotkey('ctrl+q', quit)
keyboard.add_hotkey('ctrl+alt+enter, space', u'some_callback')
keyboard.add_abbreviation('tm', u'™')
keyboard.add_abbreviation('3n', u'el3ctron') 
``` 

so, i executed on my command line ./k3y
it runs showing no error,
but when i do some abreviation (for example writting in another window 3n), or pressing some hot key ('page up, page down') nothing happens! i do not know if i am doing something wrong. :(

**Comment by boppreh** [comment]
I think your program is registering the hotkeys correctly but then exiting because it finished executing all statements.

Try to add a `input()` at the end or something similar to ensure it stops. Or test those lines in the interpreter, where it won't exit by itself.

Some other problems you may run into:

- Using `quit` as hotkey callback may not work as expected because the library uses multiple threads to read events, and the quit may just exit one of them.
- The second hotkey doesn't look right. The hotkey description is ok, but your callback is a string. Hotkeys expect an executable callback, some function that will be called. You may have confused it with an abbreviation that replaces one string for another. For that you can copy the example hotkey, the one with the `write`.

**Comment by el3ctron** [comment]
ok, thanks for your answer, i simplify the code to 3 lines like this:
 
```
#!/usr/bin/python
# coding: latin-1
import keyboard

keyboard.add_hotkey('page up, page down', lambda: keyboard.write('foobar'))
keyboard.add_abbreviation('tm', u'™')
keyboard.add_abbreviation('3n', u'el3ctron')

input()

```
then console says:

> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/threading.py", line 763, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/keyboard/__init__.py", line 109, in listen
>     _os_keyboard.listen(self.queue)
>   File "/usr/local/lib/python2.7/dist-packages/keyboard/_nixkeyboard.py", line 110, in listen
>     build_device()
>   File "/usr/local/lib/python2.7/dist-packages/keyboard/_nixkeyboard.py", line 104, in build_device
>     ensure_root()
>   File "/usr/local/lib/python2.7/dist-packages/keyboard/_nixcommon.py", line 160, in ensure_root
>     raise ImportError('You must be root to use this library on linux.')
> ImportError: You must be root to use this library on linux.

the program stops like waiting some entry, i try the abrevations "3n" and "tm" but nothing happens:

> 3n
> Traceback (most recent call last):
>   File "./k3yboard", line 14, in <module>
>     input()
>   File "<string>", line 1
>     3n
>      ^

now i execute the program in root mode, now the root warning disappears but have the exactly same behaviour:

```
Traceback (most recent call last):
  File "./k3yboard", line 11, in <module>
    input()
  File "<string>", line 1
    3n tm 3n
    ^
SyntaxError: invalid syntax
```

**Comment by boppreh** [comment]
This final error is because you are on Python2 and `input()` expects a well formed input. So while you were typing to test the abbreviations you were also feeding text into the `input()` call, and when you pressed enter it gave an error. Doesn't affect anything though because the program was already ending.

You can also replace the `input()` with `keyboard.wait('esc')`, that will block until you press 'esc'.

The abbreviations not working is a more serious problem.

Please try this simpler example and tell me if it works for you:

```
import keyboard
keyboard.add_abbreviation('123', '123456789')
keyboard.wait('esc')
```

Run this script (as sudo), type `123` followed by a space. It should insert the rest of the numbers

**Comment by el3ctron** [comment]
thanks for the example!

i run your code as root,
i type 123 followed by a space in less than 1 second
but it locks my console

i try to end the program 
with esc key but continues locked 
i try con Ctrl-c and still locked

i try to execute as my normal user, then appears the same root warning i type 123 and space quickly and same behaviour: nothing happens and console locked.

**Comment by boppreh** [comment]
Hmm, this is strange. What system are you using, and are you using any graphical interface (e.g. X)? I'm testing on my Raspberry Pi and it works as expected.

Until then try Python3, it deals with the background threads better and should not lock your console.

**Comment by jabez007** [comment]
I seem to be running into the same issue on Ubuntu MATE 16.04
I'm running python3 IDLE as sudo, but none of the hotkeys or abbreviations seem to be registering.

**Comment by boppreh** [comment]
Can you try:

```
import keyboard
keyboard.hook(print)
```
?

This should print all events received by the system. This would tell me if the problem is when receiving capturing the events or processing them.

**Comment by jabez007** [comment]
This is what I have

    import keyboard
    OUTPUT = "None"
    def write(string):
        global OUTPUT
        OUTPUT = string
        keyboard.write(string)
    keyboard.add_hotkey("Ctrl+Alt+k", write, ["hello world"])
    input()
    print(OUTPUT)

from what gets printed after my script is done, OUTPUT is getting changed so my write function is getting called but the keyboard write is not doing anything I can see.

Also, running your suggested code shows that key events are registering.

**Comment by boppreh** [comment]
Thank you, I'm checking it now.

**Comment by boppreh** [comment]
Strange, I couldn't reproduce the issue. Tried Win10 and Raspbian. Both wrote "hello world" when I pressed `ctrl+alt+k`.

Can you use the `write` call by itself, without a hotkey?

**Comment by jabez007** [comment]
Tried this

    import keyboard
    from time import sleep
    keyboard.write("Hello world")
    sleep(5)
    input("Press any key to continue....")

but nothing happens before my input hits

**Comment by boppreh** [comment]
There's still some doubt here because the "hello world" is being/would be written while nobody is listening (before the `input()` call). Could you try it without the sleep?

**Comment by jabez007** [comment]
without the sleep, the input call happens right away without "hello world" happening.

**Comment by jabez007** [comment]
Switched it around

    import keyboard
    input("Press any key to continue....")
    keyboard.write("Hello world")

and there is a small pause after the input before the command prompt comes back, but "hello world" doesn't happen

**Comment by boppreh** [comment]
Huh. I'm looking at the source code for *nix events, trying to figure out what's happening. At the moment I can only thank you for your help, jabez007.

If you have any information that you think is pertinent ("my computer has two (or zero) keyboards", "my window manager is heavily modified", "my python installation is non-standard") it could help greatly.

I'll post here again when I get an idea.

**Comment by jabez007** [comment]
Testing this out on a fresh install of Lubuntu 15.10 and got the same result. It doesn't seem like it would be the window manager, but maybe something with Ubuntu based OSes. I'll see if I can't find more.

**Comment by jabez007** [comment]
Digging in, this might be because I'm working on a laptop. 

It looks like device.write_event ultimately just picks the first item in the AggregatedEventDevice devices list, but on my laptop that appears to be the power button.  
I don't have a 'kbd' under /dev/input/by-id/ and each of my power/sleep buttons list 'kbd' as a handler in /proc/bus/input/devices. So if I'm reading through this correctly, that is where we are searching for the keyboard device but accidentally end up pick up several others.

**Comment by boppreh** [comment]
So the problem is that `write` is sending events to a keyboard device that exists but has a limited scan code range (probably just one button). I see two main solutions;

1. Try to figure out the scan codes for each keyboard device and select one with a compatible range.
2. Create a fake uinput keyboard, like it's done when there's no keyboards available, and always use that to send events.

I'll be taking a look into it later today.

Thank for the troubleshooting, jabez.

**Comment by boppreh** [comment]
Commit 456a8717b96897846152a16b7ac70cf469ffea09 fixes this issue by always sending the events through an uinput device. This has the added benefit that you can unplug your keyboard *after* the program started running.

Sorry for taking so long, I'm doing this on my free time, which is very limited at the moment.

Please tell me if this fixes your problem.

**Comment by jabez007** [comment]
no problem, I understand. I looks like that change fixes the problem I was seeing. Thank you.

**Comment by BlackHell92** [comment]
Hello ! 
I'm using Ubuntu, i've tried this library few days ago, i made a little script to write things whenever if press the hotkey 'ctrl','space'.
Everything was going allright, press_and_release(), write() was perfect... 

Until yestrurday. 

- I have no clue about what i did, but the functions write(), press_and_release(), press().... aren't working anymore, but, for some reasons, the add_hotkey() works well ! 

- Same when I try the 10_second_macro.py it works, but when i add in this code keyboard.write('test'), there's no error, the record works, but i dont see any 'test'...

I'd be glad if you could help me...
Thank you !
