### ISSUE TITLE
Hello, is this bug replicated

### ISSUE THREAD

**Issue by chaodongyang** [boppreh/keyboard#201]
XP 32 and windows7 32

**Comment by boppreh** [comment]
Hi @chaodongyang

Please don't open new tickets to ask questions about an existing issue. And please note I work on this library on my free time, for absolutely no compensation. I cannot give any guarantees on response time or fixing bugs. If this issue is critical for you, I suggest you try to fix it yourself or hire someone to do so. I'm happy to accept pull requests.

I'll continue working on the issue when possible, and will post updates on the main issue ticket.
