### ISSUE TITLE
Int too long to convert error

### ISSUE THREAD

**Issue by abhi7411** [boppreh/keyboard#208]
Hello Team,

I love this module and has been using it for long time but for some reasons I am getting this following error for which I could not find any solution please help me out.

 
_>
>   File "C:\Program Files (x86)\Python 3.7.0\lib\threading.py", line 917, in _bootstrap_inner
>     self.run()
>   File "C:\Program Files (x86)\Python 3.7.0\lib\threading.py", line 865, in run
>     self._target(*self._args, **self._kwargs)
>   File "C:\Program Files (x86)\Python 3.7.0\lib\site-packages\keyboard\__init__.py", line 292, in listen
>     _os_keyboard.listen(self.direct_callback)
>   File "C:\Program Files (x86)\Python 3.7.0\lib\site-packages\keyboard\_winkeyboard.py", line 560, in listen
>     prepare_intercept(callback)
>   File "C:\Program Files (x86)\Python 3.7.0\lib\site-packages\keyboard\_winkeyboard.py", line 553, in prepare_intercept
>     keyboard_hook = SetWindowsHookEx(WH_KEYBOARD_LL, keyboard_callback, GetModuleHandleW(NULL), NULL)
> ctypes.ArgumentError: argument 3: <class 'OverflowError'>: int too long to convert
>_

Please check the attachment the screenshot of the error too.

![image](https://user-images.githubusercontent.com/10868981/45594011-aa755900-b9b0-11e8-956c-f0f4a21526b2.png)

**Comment by vmmc** [comment]
Did you install the package with pip?
I was having this issue too while using python3.7. I believe it's been solved on the latest version so install from the master branch instead of using the PyPI package, that did it for me.
Either download https://github.com/boppreh/keyboard/archive/master.zip or clone https://github.com/boppreh/keyboard
No installation required, source files are sufficient. Also remember to uninstall the pip version.

**Comment by abhi7411** [comment]
@vmmc Hello, Thanks for taking time and commenting can you please tell me how should I install the package via the zip which you have given to me via the URL.
