### ISSUE TITLE
Keyboard-Specific Macros

### ISSUE THREAD

**Issue by glitchassassin** [boppreh/keyboard#30]
Submitting this as a potential future enhancement. I will continue to research/experiment on my end.

On Windows, keyboard-specific events can be identified using [a combination of the RawInput and KeyboardHook APIs](http://www.codeproject.com/Articles/716591/Combining-Raw-Input-and-keyboard-Hook-to-selective). This has the limitation of not capturing system shortcuts like Win+D or Alt+Tab.

**Comment by boppreh** [comment]
That sounds exactly like what I need. Thank you.

**Comment by boppreh** [comment]
I'm happy to report that this is finally working, at least as a prototype. It still needs a lot more testing, because we are now running two event listeners that have to synchronized, but it officially Works On My Machine™. I also managed to avoid the "listener in a separate dll" that the article implements, so the library is still pure python.

I'm putting more details on the original issue I opened for this ( https://github.com/boppreh/keyboard/issues/21 ) and closing this one if you don't mind.
