### ISSUE TITLE
Difference between read_hotkey and add_hotkey - NOTE: Package seems no longer maintained

### ISSUE THREAD

**Issue by danielbaumer** [boppreh/keyboard#457]
I'm using this package to control a piece of hardware:

```
adjust = True
while adjust:
    if keyboard.read_key() == 'esc':
        adjust = False

    elif keyboard.read_key() == 'left':
        move_left()
```

Now I would like to use hotkeys, e.g. something like

```
adjust = True
while adjust:
    if keyboard.read_key() == 'esc':
        adjust = False

    elif keyboard.read_key() == 'left':
        move_left()

    elif keyboard.read_key() == 'ctrl+left':    # Use read_hotkey, add_hotkey, or some other function?
        move_left_large_step()
```

From the documentation, it's not clear  which function to use and how. Specifically, what is the difference between `read_hotkey` and `add_hotkey` and which of these two is the right one?

**Comment by danielbaumer** [comment]
So...it seems like this package isn't supported/maintained any longer. What a shame!

I suggest to use pygame instead:

https://www.pygame.org/docs/ref/key.html

**Comment by boppreh** [comment]
Hi Daniel

`read_hotkey` returns when you *release* a key, and then it reports the hotkey combination that had been pressed. This is done synchronously/blocking.

`add_hotkey` can be executed either on press or release, and is asynchronous. The callback will be executed in a background thread.

Which one is appropriate depends on your use case. Also note that `keyboard.read_key()` blocks until the user presses a key, then returns that. It does not return the currently pressed key. So your chain of  `keyboard.read_key()` is almost certainly a mistake. If the user presses left + esc + left + esc, etc, it'll never enter any of the `if`s.

However, your alternative of using pygame tells me that you need to listen to events only in the local window. You can still use `keyboard`, but note that this library is meant for *global* events. It'll capture those hotkeys regardless if your game window is focused or not.

**Comment by danielbaumer** [comment]
Hey,

sorry, I thought this was not maintained after clicking through other topics (seems I only happened to hit unsolved/open questions).

So this is exactly the problem I have. Even after carefully reading through your detailed explanations several times, I **still** don't understand how to use which function.

For instance, I've already been using `keyboard.read_key()` _successfully_ in the aforementioned way, which seemed to work with individual keys: I can move the hardware pressing individual arrow keys and when I keep pressing a key, the hardware keeps moving (as fast as Python loops through the `while` loop as shown above). And if `esc` is pressed, the loop exits as expected.

The problem is, however, that none of the key combinations work (e.g. `ctrl+left`).

I also don't understand your example, i.e. why pressing `left+esc+left+esc` will **never** enter any of the `if`s, since both the "`left`-`if `" and "`esc`-`if `" **are** entered upon pressing `left` or `esc` (it's only that pressing `esc` will immediately exit the loop - as intended!).

Furthermore, I don't understand the issue with "local"/"global" events and windows, because toggling `suppress=True` seems to limit the scope to the active window (at least the documentation seems to suggest this). So why is this an issue with `keyboard` and not e.g. with `pygame`?

Finally, maybe it wasn't quite clear how I'm trying to integrate your package. Let me briefly explain: I need to move a piece of hardware using different key combinations such that when I press a key once, the hardware moves one step, and if I keep a key pressed, the hardware continues to step through its range of motion until the key is released. Also, by using key combinations, the step size (and thereby the speed of movement) can be varied. It's also important that I only want something to happen upon a key down, not a key up/release event. So:

_- Press key once => Do one step
- Keep key pressed => Keep stepping until key is released
- Press key combination once => Do one large step
- Keep key combination pressed => Keep stepping with large step size until key combination is released_

Hope it's a little clearer now.

**Comment by danielbaumer** [comment]
PS.: I assumed that `left+esc+left+esc` means pressing (and releasing) them sequently as such key combination wouldn't be possible

**Comment by boppreh** [comment]
> I also don't understand your example, i.e. why pressing left+esc+left+esc will never enter any of the ifs, since both the "left-if " and "esc-if " are entered upon pressing left or esc (it's only that pressing esc will immediately exit the loop - as intended!).

With this code in mind, imagine what happens if I press <kbd>left</kbd>, and holding it, then press <kbd>esc</kbd>:
```
while adjust:
    if keyboard.read_key() == 'esc':
        ...
    elif keyboard.read_key() == 'left':
        ...
```

The first check will evaluate `keyboard.read_key()` to <kbd>left</kbd>, so it doesn't enter the loop. Then the next test will evaluate `keyboard.read_key()` again, because it's a new function call, and it results in <kbd>esc</kbd>, so it doesn't enter the conditional either.

Now the "while" loop continues, and you release <kbd>left</kbd> first, then <kbd>esc</kbd>. The same thing will happen, but this time with key_up events.

So you pressed and released both esc and left, but none of the conditionals were activated. The problem here is caused by checking for a new key event on each conditional, instead of reading it once, storing in a local variable, and comparing that:

```
while adjust:
    key = keyboard.read_key()
    if key == 'esc':
        ...
    elif key == 'left':
        ...
```

I believe you it works, but you may have noticed that sometimes it takes a bit longer for an event to register, or that you have to hold (and generate more events!).

> Furthermore, I don't understand the issue with "local"/"global" events and windows, because toggling suppress=True seems to limit the scope to the active window (at least the documentation seems to suggest this). So why is this an issue with keyboard and not e.g. with pygame?

From the docs:

> `suppress` defines if successful triggers should block the keys from being sent to other programs.

What is meant here is that if you create a suppressing hotkey for <kbd>left</kbd>, for example, *no other programs will ever receive a <kbd>left</kbd> event*. The user could open another game, press left, and the player would move in *your* game.

This library is for handling global events, for example:

- I want this script to open my browser, navigate to a certain page, press ctrl+a then ctrl+c, read the clipboard, and save the contents to a file.
- Whenever I type "wierd" I want to backspace those letters and replace it with "weird".
- I want to record everything I type to perform statistical analysis on my typing speed.
- My language has hard-to-type letters and I don't want to switch keyboards all the time, so when I type "coracao" I want it to be replaced with "coração".

And so and so on.

You could use it for a game, there's nothing preventing you, but you'll run into a lot of unintended consequences (e.g. what happens if the player minimizes your game and tries to do something else).

**Comment by danielbaumer** [comment]
> With this code in mind, imagine what happens if I press left, and holding it, then press esc:
> 
> ```
> while adjust:
>     if keyboard.read_key() == 'esc':
>         ...
>     elif keyboard.read_key() == 'left':
>         ...
> ```
> 
> The first check will evaluate `keyboard.read_key()` to left, so it doesn't enter the first conditional.

...it's not meant to

> Then the next test will evaluate `keyboard.read_key()` again, because it's a new function call, and it results in esc, so it doesn't enter the second conditional either.

...again, it is not meant to

> Now the "while" loop continues, and you release left first, then esc. The same thing will happen, but this time with key_up events.

Isn't it possible to suppress key up events?

> So you pressed and released both esc and left, but none of the conditionals were activated.

No, in fact **both** conditionals were activated subsequently in the order of the keys pressed (as intended)! 

> The problem here is caused by checking for a new key event on each conditional, instead of reading it once, storing in a local variable, and comparing that:
> 
> ```
> while adjust:
>     key = keyboard.read_key()
>     if key == 'esc':
>         ...
>     elif key == 'left':
>         ...
> ```

Thanks, I will try this right away.
 
> I believe you it works, but you may have noticed that sometimes it takes a bit longer for an event to register, or that you have to hold (and generate more events!).

Very true - could you explain why this happens (i.e. these lags)? I'd like to understand the "mechanics" behind the issue

> You could use it for a game or to control a piece of hardware, there's nothing preventing you, but you'll run into a lot of unintended consequences. For example, imagine what happens if the player minimizes your program and goes to type message to their friends.

Good point, but what will **really** happen...if the user is inside the `while` loop and, upon a specific key press, a function is called (e.g. a measurement routine taking 15 min) - will an additional key press during the execution of the function actually be registered as such? Won't the "pointer" of the Python interpreter not stay on the function being executed until it is finished and returns to the level of the `while` loop? I.e. will a key press during those 15 min **really** initiate additional, unintended hardware movements (e.g. if the user starts typing in a messenger and happens to hit an arrow key) or will those keys bound to `keyboard` just stay dead for the duration of the function call?

**Comment by danielbaumer** [comment]
PS.: To make the issue quite clear, I'm actually trying to reproduce the most basic keyboard functionality identical to what happens when someone is typing into Notepad: Press a key once => a letter is typed. Keep the key pressed => the letter gets repeated until key is released. Now simply replace the letter being typed with a motor doing a step.

**Comment by danielbaumer** [comment]
Also, btw, the main issue is that **key combinations** don't work. Any idea how to include this functionality in a simple way?

**Comment by boppreh** [comment]
> Very true - could you explain why this happens (i.e. these lags)? I'd like to understand the "mechanics" behind the issue. For instance, I need to keep esc pressed for about half a second for it to register and I don't understand why. Is it an additional latency introduced by Python having to call read_key at each conditional?

That's what I tried to explain before. This is not a performance problem, this is a logical problem. I don't think you got my explanation regarding the "left" and "esc" events.

The source of the delay is because your program receives keyboard events in three scenarios: key was just pressed (emitted immediately), key is being held and repeated events are sent (like notepad, takes about half a second), and key is released.

If the conditional that the event is meant for missed it, you have to either release the key or hold it for some time before the conditional has another chance at catching it. That's where the delay comes from.

> PS.: To make the issue quite clear, I'm actually trying to reproduce the most basic keyboard functionality identical to what happens when someone is typing into Notepad:

If you are trying to process events local to your program, I highly, highly recommend not using `keyboard`. In your case PyGame may actually be a better option, or any of the slightly hacky solutions to get individual key events *when your window has focus*, like getchr or ncurses.

Regarding the 15-minute routine, I also highly recommend not running anything long running (more than a few hundred milliseconds) in the same thread that is checking for events. You should either start a separate thread on every event (and have potentially multiple 15-minute routines running at the same time), or send an event to a permanent separate thread telling it to start the routine (and have only one such routine at a time).

**Comment by danielbaumer** [comment]
But how does this code snippet receive three scenarious at the same time? I didn't put anything in it (explicitly) that would cause this behavior, so is this something about how `read_key` is designed?

I'm not sure if you can empathize with my problem grasping what determines the behavior of `read_key`, but let me briefly give you an example the same snippet:

```
adjust = True
while adjust:
    key = keyboard.read_key(suppress=True)
    if key == 'esc':
        adjust = False

    elif key == 'left':
        move_left()

    elif key == 'ctrl+left':    # Use read_hotkey, add_hotkey, or some other function?
        move_left_large_step()
```

Now let's see what happens step by step. We first enter the loop with `adjust` set to `True` and Python keeps looping.

1.) While looping, the user presses and releases `left`. `read_key` recognizes this and `move_left()` is evaluated.
2.) After evaluation, we're back in the loop.
3.) While looping, the user presses and releases `ctrl+left`. `read_key` recognizes this and `move_left_large_step()` is evaluated.
4.) After evaluation, we're back in the loop.
[Repeat as many times as you wish...]
5.) While looping, the user presses and releases `esc`. `read_key` recognizes this and `adjust` is set to `False`.
6.) The pointer reaches the beginning of the loop and exits it, because `adjust` is no longer `True`.

Similarly, if a key is pressed, but **not** released, every time the loop starts at the beginning, `read_key` again recognizes the pressed key and evaluates the associated function.

Where in this sequence does now a "key release" event come into play? Are you saying that `read_key` evaluates the associated function both upon the key being pressed **and** being released, i.e. effectively twice with every key strike?? Or maybe even three times with every key strike, because "key continuously being pressed" is another separate event? So if the user strikes `left`, `move_left()` gets evaluated three times in a row?

> If the conditional that the event is meant for missed it, you have to either release the key or hold it for some time before the conditional has another chance at catching it.

This is what I don't understand: I don't have any conditionals for "key released" events. Also, how can `read_key` possibly "miss" anything? And even if `read_key` would be waiting for a "key release" event after each "key pressed" event, I never observed `read_key` being permanently "stuck" in a "key pressed" state (e.g. `move_left` being evaluated indefinitely). I didn't think of `read_key` as something like a state machine where some internal state is set to either "pressed" or "released" and then held in that state indefinitely.

> Note that the whole concept of "missing an event" only happens here because you are calling `get_key` multiple times in your while loop.

But why would anything be "missed" just because the function is called multiple times? Is there some inherent flaw or rule within Python that causes functions to "crash" if they are called several times within a loop? Some kind of race condition or something going wrong in the RAM?

**Comment by danielbaumer** [comment]
> Note that the whole concept of "missing an event" only happens here because you are calling get_key multiple times in your while loop.

...wait, are you saying that `read_key` should be placed **outside** the `while` loop??

Like this:

```
key = keyboard.read_key(suppress=True)

adjust = True
while adjust:
    if key == 'esc':
        adjust = False

    elif key == 'left':
        move_left()

    elif key == 'ctrl+left':    # Use read_hotkey, add_hotkey, or some other function?
        move_left_large_step()
```

**Comment by danielbaumer** [comment]
There are several issue being raised that appear to be closely related to the problems I've been trying to describe here, e.g.

https://github.com/boppreh/keyboard/issues/442
https://github.com/boppreh/keyboard/issues/441

From the lack of solutions there and the lack of help here, I cannot help but conclude that this package is either not ready for being published on GitHub or it's no longer maintained. It's simply not acceptable for such elementary functions not to be working. My suggestion is to do some serious bugfixing first before publishing.

**Comment by boppreh** [comment]
Hi Daniel. No, don't put the `read_key` outside the while loop. What I meant is that you should have only *one* `read_key` inside the loop, and not one for each condition.

The issues you linked are unrelated because they happen when handling registered hotkeys (`add_hotkey`), which you are not using.

> I don't have any conditionals for "key released" events.

`read_key` returns the name of the next key event, regardless of type. This includes "key released" events, and "key is being held down" events. You can run `python -m keyboard` to see what sort of events are reported.

> Also, how can read_key possibly "miss" anything?

`read_key` doesn't miss events, the way you structured your conditional does.

```
if keyboard.read_key() == 'left':
    print('LEFT!')
elif keyboard.read_key() == 'esc':
    print('ESC!')
```

Is going to wait for *two* events (be they key press, hold, or release), because there are two calls to `read_key()`. If you press 'esc' then 'left' while holding them both, the first conditional will evaluate to False because 'esc' != 'left', and the second conditional will also evaluate to false because 'left' != 'esc'. Therefore you "missed" the event.

The correct would be:

```
key = keyboard.read_key()
if key == 'left':
    print('LEFT!')
elif key == 'esc':
    print('ESC!')
```

**Comment by danielbaumer** [comment]
> Is going to wait for two events (be they key press, hold, or release), because there are two calls to read_key(). If you press 'esc' then 'left' while holding them both, the first conditional will evaluate to False because 'esc' != 'left', and the second conditional will also evaluate to false because 'left' != 'esc'. Therefore you "missed" the event.

Sorry, but this is just nonsense! Here, have another snippet:

```
import keyboard

while True:
    if keyboard.read_key() == 'left':
        print('LEFT!')
    elif keyboard.read_key() == 'esc':
        print('ESC!')
```

Seriously...it does NOT get simpler than this! Please save this into a PY file and run it from the console. What you will observe are two things:

1. Pressing and releasing `left` indeed triggers **two** events (2 x "LEFT!" printed to screen), while pressing and releasing `esc` triggers only **one** event (1 x "ESC!" printed to screen). Why?
2. Pressing `esc` and `left` while holding both (as you suggested) does **not** cause both conditionals to evaluate to `False`. Instead, first "ESC!" gets printed to screen multiple times, then "LEFT!" gets printed to screen multiple times and vice versa. Note that "ESC!" still gets printed only once upon each stroke of `esc`.

Now, try the same thing with this snippet, which uses only one call of `read_key()` at the beginning of the loop:

```
import keyboard

while True:
    key = keyboard.read_key()
    if key == 'left':
        print('LEFT!')
    elif key == 'esc':
        print('ESC!')
```

This shows almost the same behavior, **except** that now `esc` behaves identical to `left` in the sense that both key press and release events trigger a print to screen (i.e. 2 x "ESC!" and 2 x "LEFT!" for each keystroke/release). Now, I don't understand why the first snippet causes the `esc` key-up event to be suppressed, but the point is that I don't see anything getting "missed" by either code pattern (i.e. all key-down events appear to get registered).

**Most importantly**:

1. I still don't know whether to use `read_key` or `add_hotkey`
2. I still don't know why key combinations won't register

I can tell by your responses that you seem to completely lack the ability to empathize with the issue at hand:

> PS.: To make the issue quite clear, I'm actually trying to reproduce the most basic keyboard functionality identical to what happens when someone is typing into Notepad:
> 
> Press a key once => a letter is typed
> Keep the key pressed => the letter gets repeated until key is released
> Press shift + key => a capital letter is typed
> Keep shift + key pressed => the capital letter gets repeated until keys are released
> Now simply replace the letter being typed with a motor doing a step and capitalization with increasing the step size. Easy!

An additional source for confusion stems from the fact that the name `add_hotkey` suggests that this function is used to **store** key combinations (which can then be registered e.g. using `read_key`). And indeed, `read_key` seems to contain a list of recognized keys that it is able to register, so we only need to check how `read_key() == KEY_NAME` evaluates. In contrast to this, the documentation on `add_hotkey` seems to suggest that `add_hotkey` requires to be called for each key combination separately, i.e. contrary to what it name suggests, it doesn't store any key combinations, but requires the key combination to be handed over as an argument.

And guess what, your solution of calling the function only once at the beginning of the loop does NOT work with `add_hotkey` to begin with (please correct me if I'm wrong!).

So, please...if you publish something online for other people to use and someone raises an issue, try to empathize with the problem at hand. Just look at this conversation and the sheer amount of text that is necessary to convey even the simplest issue (as quoted above). Maybe I'm too stupid, but I simply cannot derive any useful answers from the almost non-existent documentation and trying to convey the issue here is also not an easy job. One cannot expect users to analyze the entire source code in order to be able use a package. I hope you understand

**Comment by boppreh** [comment]
Your initial code is broken in the exact way I described. Here's a test case that reproduces 100% of the time:

```
import keyboard

while True:
    if keyboard.read_key() == 'left':
        print('LEFT!')
    elif keyboard.read_key() == 'right':
        print('RIGHT!')
    elif keyboard.read_key() == 'up':
        print('UP!')
```

Press "up", then "right", then "left", without holding them. You'll see *nothing* will be printed. You're free to re-read my comments above to understand why.

-----

There are two main ways to react to events using `keyboard`: using either asynchronous calls (`add_hotkey`, `on_key_press`, etc), or synchronous calls (`read_key`, `is_pressed`).

This is how I would do with asynchronous calls:

```
import keyboard

keyboard.on_press_key('left', lambda e: print('Start moving left'))
keyboard.on_release_key('left', lambda e: print('Stop moving left'))
keyboard.on_press_key('shift', lambda e: print('Start running'))
keyboard.on_release_key('shift', lambda e: print('Stop running'))

keyboard.wait()
```

And this is how I would do synchronous calls:

```
import keyboard, time

while True:
    if keyboard.is_pressed('left'):
        print('Move left')
    if keyboard.is_pressed('shift'):
        print('Run')
    time.sleep(0.1)
```

In your specific case, though, using `keyboard` at all is hacky because you're capturing events from your entire system, instead of just the events sent to the running program.
