### ISSUE TITLE
Do not require root for monitoring keys on Linux

### ISSUE THREAD

**Issue by dragonDScript** [boppreh/keyboard#479]
I'm developing a desktop app with PySide6 and keyboard. I need to listen to a key to launch my app. I don't want to require root previlidges on Linux. Is there any way to do so? It is a huge security risk.

**Comment by boppreh** [comment]
You need to be in the `input` group to read/write the device files, and be root to call `dumpkeys` which gives the name of each key.

If you declare all your hotkey in terms of scan_codes and add the user to group `input`, you can disable the check.

Please note that anything written with `keyboard` is already very security sensitive, because you can read passwords written anywhere, or send fake keypresses to perform attacks just like [Rubber Ducky](https://shop.hak5.org/products/usb-rubber-ducky-deluxe).

**Comment by dragonDScript** [comment]
> You need to be in the `input` group to read/write the device files, and be root to call `dumpkeys` which gives the name of each key.
> 
> If you declare all your hotkey in terms of scan_codes and add the user to group `input`, you can disable the check.
> 
> Please note that anything written with `keyboard` is already very security sensitive, because you can read passwords written anywhere, or send fake keypresses to perform attacks just like [Rubber Ducky](https://shop.hak5.org/products/usb-rubber-ducky-deluxe).

Is this a code thing or can I modify keyboard? It's a desktop app, that needs to be simple. So it's hard to get everyone to do this.

**Comment by adabru** [comment]
As you are developing a desktop app maybe you can use polkit. Like you would get a user prompt asking for the user password to access the file.
