### ISSUE TITLE
You do not need to be root to access /dev/input/*

### ISSUE THREAD

**Issue by lyiriyah** [boppreh/keyboard#489]
`/dev/input/*` can be used if you are a member of whatever group owns the event handlers, in my case `input`. You can check with `ls -l /dev/input | grep -v by- | head -n 1 | awk '{ print $3 }'`.

**Comment by lyiriyah** [comment]
I'll start working on a way to check file groups and user groups and compare them now

**Comment by lyiriyah** [comment]
Closing. Duplicate of #312. This really is a large issue. It makes this library untenable for use in many circumstances, which is a shame since it's so good. I guess you can change `/dev/uinput`'s group but that resets every reboot. I think I'll just use `evdev`.

**Comment by boppreh** [comment]
It's not just `/dev/input` that requires special privileges, it's `dumpkeys`. And I couldn't find any specific group that allows `dumpkeys` usage without literally being root, and not using this external program means there's no way to map scan codes to key names.

The only way forward I see is to enable an alternative X-based input event manager, but that's also a (partially) doomed proposition due to the rise of Wayland.

Suggestions welcome.

**Comment by glyh** [comment]
FYI, https://github.com/gvalkov/python-evdev
