### ISSUE TITLE
The problem of running in root privileges 

### ISSUE THREAD

**Issue by chuzui** [boppreh/keyboard#49]
Hi, thanks for this useful library. I wrote a script to google the selected text when pressing the hot keys. After running it in root privileges,  instead of opening my default web browser, it opens another one.

I added some codes to the script to drop the root privileges. Then the script worked perfectly.
```
uid = pwd.getpwnam('my_user_name')[2]
os.setuid(uid)
```

 But it is possibly not a good idea to enter my user name. So is there another way to achieve this?

**Comment by boppreh** [comment]
One of the next features to be implemented is use X as a backend instead of the raw device files. This would allow the library to run with regular user privileges. It would not work for systems without a graphical interface, but since you are using a browser this doesn't seem to be an issue here.

So, it's on the roadmap and has a high priority.
