### ISSUE TITLE
Only last hotkey from array works 

### ISSUE THREAD

**Issue by Chimildic** [boppreh/keyboard#493]
If `add_hotkey` with `for` loop, will work only last hotkey. If `add_hotkey` call separately, will correct. What's my mistake?

In the demo, both works `z` and `x`. But when press `f4` always `f8` printed.
```python
from keyboard import add_hotkey, wait, call_later
from time import sleep

def on_callback(key):
    print('pressed', key)
    sleep(5)
    print('end for', key)

keys = ["f4", "f8"]
for key in keys:
    add_hotkey(key, lambda: call_later(on_callback, args=(key,)))

add_hotkey("z", lambda: call_later(on_callback, args=("z",)))
add_hotkey("x", lambda: call_later(on_callback, args=("x",)))

wait('esc')
```

**Comment by boppreh** [comment]
That's due to [Python's late binding](https://stackoverflow.com/questions/233673/how-do-lexical-closures-work), due to the use of the iteration variable `key` inside a lambda. It's well known gotcha in Python and a quite unfortunate language decision.

```python
for key in keys:
    add_hotkey(key, lambda: call_later(on_callback, args=(key,)))
                                                          ^^^
```
The `key` name declared in the for loop acts like a global variable, being reassigned on every iteration. So the reference highlighted above always contains the value of the last iteration, in your case "f8".

A hacky but quick solution is to create a new name, inside the loop, that gets re-created on every iteration and hence sticks to their value.

```python
for key in keys:
    add_hotkey(key, lambda key=key: call_later(on_callback, args=(key,)))
                              ^^^^
```

I'm closing this ticket since it's only tangentially related to the library, but I hope the comment above can help you fix your issue.
