### ISSUE TITLE
mouse support or pre-release?

### ISSUE THREAD

**Issue by xiangxw** [boppreh/keyboard#51]
Hi, when can we use this library with mouse support? Looking forward to use it. Thanks.

**Comment by boppreh** [comment]
Hi

Take a look at https://github.com/boppreh/keyboard/blob/master/keyboard/mouse.py

It's available as `from keyboard import mouse`. It's not official, but functional.

**Comment by xiangxw** [comment]
I see, thanks a lot. 
By the way, how can I identify the hwnd of a mouse or keyboard  event? 
Can this library be used in PyQt program ?

**Comment by boppreh** [comment]
The events detected are global. There's no notion of "window", or window handlers. You can call `GetForegroundWindow`[https://msdn.microsoft.com/en-us/library/windows/desktop/ms633505(v=vs.85).aspx] to get the foreground window, maybe through ctypes or win32gui, but there's no direct support in this library.

And I'm not sure if it would work with a PyQt program, because the Windows backend that handles keyboard events is its own Windows message-loop (https://github.com/boppreh/keyboard/blob/master/keyboard/_winkeyboard.py#L430). That may or may not interfere with the Qt event loop, you would have to test it. If you do, please post the results, that would be very useful to know.

If it doesn't work for PyQt, you may have more luck with a PyQt specific solution, such as https://pypi.python.org/pypi/PyGlobalShortcut/0.2.3 .

**Comment by xiangxw** [comment]
Hi, keyboard can be used with PyQt. But it will freeze input dialog sometimes, and I can't move the mouse. Maybe we should not call SetWindowsHookEx in anothor thread? or can we call SetWindowsHookEx in main thread and use Qt's main loop to do pythoncom.PumpMessages(), just like pyHook do? Thanks.

**Comment by s0hvaperuna** [comment]
I solved the freezing by moving `pythoncom.PumpMessages()` to the Qt loop using a `QTimer`
```
timer = QTimer()
timer.timeout.connect(pythoncom.PumpWaitingMessages())
timer.setInterval(10)  # Call pythoncom.PumpWaitingMessages() around 100 times per second
timer.start()
```
This seems to fix the problem for me but I haven't done any extensive testing so it might still freeze in some situations.

**Comment by Doom8890** [comment]
What are the requirements to consider mouse for release, at least the Windows version?

Since I need mouse hooks for the project I'm working on, I might contribute on the way as well(even though the functionality implemented so far is enough).

**Comment by boppreh** [comment]
@Doom8890 It's already available as `from keyboard import mouse`. There's no documentation page, but you can easily see what functions are available at https://github.com/boppreh/keyboard/blob/master/keyboard/mouse.py .

```
from keyboard import mouse
mouse.move(100, 200)
mouse.double_click()
```

You can also listen for events, record and replay macros. It's quite similar to `keyboard`, but simpler because there's less buttons and no layouts to worry about.

It's not "official", and not documented in the main page, because I think `from keyboard import mouse` looks silly and I can't think of any appropriate package name that isn't in use and wouldn't cause confusion with other similar packages.

**Comment by boppreh** [comment]
Good news everyone!

I've contacted the current owner of the `mouse` package and they agreed to transfer ownership of the name. So I'll be releasing a sister library to `keyboard` under the name of `mouse`, containing the code that's currently at `from keyboard import mouse`.

This is by far the best resolution I could hope for. Stay tune for news.

**Comment by klvbdmh** [comment]
> Is there anything you need that is not available at the moment?

I'm not sure if I should post here, open another issue, or wait for the ownership transfer and a new repo. Anyway, I would like a `mouse.drag` function. It's nothing more than a combination of `press`, `move`, and `release`, but I find writing an using this helper function a lot.

**Comment by boppreh** [comment]
> I'm not sure if I should post here, open another issue, or wait for the ownership transfer and a new repo. Anyway, I would like a mouse.drag function. It's nothing more than a combination of press, move, and release, but I find writing and using this helper function a lot. 

Here; https://github.com/boppreh/keyboard/commit/85a41621c0c02c55e4089f7d5ecef706f7de9409

Unrelated, I'm getting some errors on the mouse listening parts. I'll have to investigate.

**Comment by klvbdmh** [comment]
Awesome, thanks!

**Comment by boppreh** [comment]
Now available at https://github.com/boppreh/mouse , though it's still somewhat experimental.
