### ISSUE TITLE
keyboard.add_hotkey activation threading problem

### ISSUE THREAD

**Issue by jimmycorkhill** [boppreh/keyboard#73]
When I activate a hotkey it calls the specified function but it bugs out a lot. With a tkinter label it gave an error about the main loop thread and with the sys.exit function it hangs.

I'm guessing this is my fault but I'm not sure how I might fix this? Can you give me an idea of how this might have happened?

**Comment by jimmycorkhill** [comment]
I used this workaround for the time being

    if keyboard.is_pressed('end') and not keypressed :
        quitbot()
    keypressed = keyboard.is_pressed('end')

I understand that this may stall at some point though.

Btw, I just wanted to say that this is a great library for Python and you've saved me a lot of time. Well done.

**Comment by glitchassassin** [comment]
The difficulty, as you've discovered, is that hotkey callbacks operate on a different thread, and Tkinter doesn't play nicely with multiprocessing.

If you're just trying to abort the script, I've found this usually works:

    import thread
    import keyboard
    def _abort_script():
        thread.interrupt_main()
    keyboard.add_hotkey("alt+shift+c", _abort_script, suppress=True)

`thread.interrupt_main()` sends an interrupt (like pressing Ctrl+C) to the main thread, which (unless you have some kind of exception handling for that) causes it to terminate immediately.

If you're trying to do something more complex, there are other ways to work around Tkinter's threading limitations.

**Comment by SomaBots** [comment]
I need to work around tkinter's limitations, can you help point me in the right direction? Using add_hotkey I get this issue with tkinter    

```
return self.tk.call('wm', 'geometry', self._w, newGeometry)
RuntimeError: main thread is not in main loop
```

**Comment by glitchassassin** [comment]
Oh man, it's been a long time since I've looked at this.

Check out the top answer to [this StackOverflow question](https://stackoverflow.com/questions/44190081/python-3-6-tkinter-and-multiprocessing). The basic idea is that you can't manipulate any tkinter widgets except in the main loop - so if your threads (including `keyboard`) need to manipulate tkinter widgets, they'll actually have to use Python's multiprocessing features to pass a message over to the tkinter main loop to be handled there.

Good luck!

**Comment by boppreh** [comment]
Since this is not an issue with `keyboard` itself, I'm closing this issue.
