### ISSUE TITLE
Question mark

### ISSUE THREAD

**Issue by Myv-hs** [boppreh/keyboard#84]
I've found an issue with two characters: the eponymous question mark and the asciicircum. I've made a little script using socket and keyboard (look in my python repository), so that I can use one keyboard for several computers; essentially Synergy but I have no money.
Anyway, at the receiving end, when a question mark or asciicircum are used in keyboard.press(key) it throws me this error.

Traceback (most recent call last):
  File "SKServer.py", line 58, in <module>
    down(instring.split(' ')[1])
  File "SKServer.py", line 6, in down
    if not keyboard.is_pressed(key):
  File "C:\Users\WASD\AppData\Local\Programs\Python\Python36\lib\site-packages\keyboard\__init__.py", line 176, in is_pressed
    if matches(event, key):
  File "C:\Users\WASD\AppData\Local\Programs\Python\Python36\lib\site-packages\keyboard\__init__.py", line 156, in matches
    return matched_name or _os_keyboard.map_char(normalized)[0] == event.scan_code
  File "C:\Users\WASD\AppData\Local\Programs\Python\Python36\lib\site-packages\keyboard\_winkeyboard.py", line 493, in map_char
    raise ValueError('Key name {} is not mapped to any known key.'.format(repr(name)))
ValueError: Key name '?' is not mapped to any known key.

It could just be a windows thing, but when I tried to test with linux on the receiving end, it wouldn't work with two keys pressed as it does on windows.

**Comment by boppreh** [comment]
Hi @Myv-hs 

Sorry for the delay, this one was quite tricky. It seems that question mark is the only character that is missed in the Windows backend. There are two possible virtual key codes, and things get ugly.

I've added code to try more virtual key codes when building the table of key names. It's available in the `master` branch, so you can either clone the repository or perform the change manually (https://github.com/boppreh/keyboard/commit/ae0b17450eca321e4921447ba73c02954298d309).

It fixed the issue on my side. Can you test if it works for you, and more importantly, doesn't break the rest of your setup?

**Comment by Myv-hs** [comment]
Hello @boppreh 

Sorry I took so long to respond, but I wasn't around a computer for the last week.

Good news is it didn't break my setup at all, bad news is it didn't seem to fix it on my end. Worst news is, the issue seems more complex now.
On my keyboard the question mark is shift+/, and when I do that combo, it comes up as a question mark in the sending script, when I print the decoded string that comes through on the recieving end it shows as a question mark, but when it goes keyboard.press(questionmark) it outputs "/". It seems to ignore the shift state somehow.
I'll look at it some more at my end, see if there's something I'm doing wrong and maybe look for a workaround.

**Comment by boppreh** [comment]
Two questions:

- Does `keyboard.press('?')` work on the receiving end if you type it into the interpreter?
- Are both sides running Windows, and did you update the library on both?

**Comment by boppreh** [comment]
Sorry, I got a bit confused. I think the library is actually doing the right thing here.

Most functions in this library are interested in the physical keys for hotkeys, and not typing a specific character. So `press('?')` is actually equivalent to `press('/')` (in your layout), because both characters are mapped to the same physical key. Otherwise `add_hotkey('shift+/', ...)` would never work.

There are a few functions that *do* care accurate character mapping, including `write`. If you want to type `?`, use `write('?')` instead of `send('?')`.

But as I understand, what you want is accurate *key* mapping, not *character*, because you are sending all key events from one computer to another. For example, if linux sends "shift, ?", windows should not press "shift, shift /". So the behavior of `press('?')` maps the expectation.

If the receiving side is not printing '?' after receiving 'shift+?' or 'shift+/', I would check if shift is being pressed correctly.

Does that make sense?

**Comment by Myv-hs** [comment]
Ok thanks, I just used keyboard.write as a work around c1589a3
