### ISSUE TITLE
Permission denied and not receiving events (Ubuntu 14.04.1)

### ISSUE THREAD

**Issue by centralniak** [boppreh/keyboard#9]
Running this code:

```
import keyboard


keyboard.add_hotkey('f4', lambda: print('f4'))
keyboard.add_hotkey('f5', lambda: print('f5'))
keyboard.add_hotkey('f6', lambda: print('f6'))

keyboard.wait('esc')
```

Results in the following in the stderr:

```
Permission denied (/dev/input/by-path/platform-i8042-serio-0-event-kbd). You must be sudo to access global events.
```

Also the callbacks are never executed.

Let me know if I can give more details.

**Comment by caenyon** [comment]
Like the error message says:
You must be root to access the global message queue. 

Run your script as root:
sudo python your_script.py

**Comment by boppreh** [comment]
Thanks for answering this one, @caenyon .

@centralniak , unfortunately the current method requires opening files that are owned by root. Therefore the library requires scripts to be run under `sudo` as @caenyon mentioned. If the question is only about this, I'm closing the issue. This will be noted in the docs when I get time to write them.

Any suggestions on alternative methods that don't require `sudo` (without sacrificing correctness) are welcome.

(sorry for the hiatus, I've been really busy because of other stuff)

**Comment by centralniak** [comment]
Thanks you both @caenyon @boppreh - I appreciate such a prompt answer.

Yes the issue is just about that - I was confused by the fact that it wasn't documented.

P.S. For my application I will just use pynput for now - I love the simplicity of your api though!

**Comment by boppreh** [comment]
Thank you. I'll be closing the issue now, but feel free to open any new issues if you have more questions or suggestions.

Good luck with your project!
