### ISSUE TITLE
Error 13 after packed with pyinstaller

### ISSUE THREAD

**Issue by skys215** [boppreh/keyboard#94]
Hi,

I recently wrote a program with PyQt5 which uses `keyboard` module. The program run well as `.py` with `sudo`, before packing as `.app` file with `pyinstaller`. After packing, the console shows that I'm not running the `.app` as administrator. But, the error shows even I run with `sudo`.

I submit new issue on the `pyinstaller`. It's been a month that I posted. Then I tried to include the `keyboard` into source code instead of importing as a installed third-party module. But the problem remains. So I'm guessing that maybe there's something to do with the module itself.

To reproduce the problem, see [the issue I wrote on the `pyinstaller` project](https://github.com/pyinstaller/pyinstaller/issues/2742).
    
 Let me know if you need more information.

Thanks.

**Comment by genequ** [comment]
I got the same error when runing keyboard from another project, https://github.com/glitchassassin/lackey/issues/108

**Comment by glitchassassin** [comment]
If you're not using the key listener, you can safely ignore the error: it should have no impact on running your program.

I am not sure about the steps needed to run a `pyinstaller` build as sudo. There are some ideas on [this StackOverflow thread](https://stackoverflow.com/questions/5747007/get-root-dialog-in-python-on-mac-os-x-windows), but I haven't tried any of them myself.

It might be a good idea to see if `keyboard` can be refactored to only launch the root-level thread if the listener is being activated, rather than by default; this will eliminate those extra errors. In addition, it looks like the root privilege escalation must happen after the program is loaded: if so, the thread really shouldn't be launched until that escalation has had a chance to happen anyways.

**Comment by skys215** [comment]
So what should I do fix the problem or test some code?

**Comment by glitchassassin** [comment]
Good call, @boppreh, I had forgotten about that.

So @skys215, to fix the problem, the short answer is "run the script as root." It seems like that might be a bit more complicated with pyinstaller, but it doesn't seem to be an issue with the `keyboard` library, so you'll probably find better support for your question from the pyinstaller project.

Good luck!

**Comment by skys215** [comment]
@glitchassassin 
As I mentioned in [the issue that I reported on pyinstaller project](https://github.com/pyinstaller/pyinstaller/issues/2742), I have run the project as root, but it still got no permission to bind the hotkey.
Or maybe I should run `getuid()` or some function else to check if I'm running the program as sudoer or not even I run with sudo?
I'll check that later.
